#!/usr/bin/env bash
wm=monsterwm
ff="/tmp/$RANDOM.monsterwm.fifo"

tags=(' term' ' web' ' fm' ' mail' ' foo' '')
#layouts=('TILE' 'MONOCLE' 'BSTACK' 'GRID' 'FLOAT') 
#layouts=('\ue002' '\ue001' '\ue003' '\ue005' '\ue006')
layouts=('' '' '' '' '' '')

[[ -p $ff ]] || mkfifo -m 600 "$ff"

function statusbar {
# mpd status
music="$(mpc current -f "%title% #\f8by #\f9%artist%")"
if [ -z "$music" ]; then music="[stopped]" mstat=""
else
    mstat="$(mpc | sed -rn '2s/\[([[:alpha:]]+)].*/\1/p')"
    [ "$mstat" == "paused" ] && mstat="" || mstat=""
fi

bat="$(acpi | awk '{print $4,$5}')"
date="$(date +"%a %d %b, %R")" 
mem=$(free -m | awk '{print $3}' | head -2 | tail -1) 
#mem=$(free -m | awk '/buffers\/cache/ {print $3 MB}')
cpu=$(eval $(awk '/^cpu /{print "previdle=" $5 "; prevtotal=" $2+$3+$4+$5 }' /proc/stat); sleep 0.4; eval $(awk '/^cpu /{print "idle=" $5 "; total=" $2+$3+$4+$5 }' /proc/stat); intervaltotal=$((total-${prevtotal:-0})); echo "$((100*( (intervaltotal) - ($idle-${previdle:-0}) ) / (intervaltotal) ))")
vol=$(amixer get Master | egrep -o '[0-9]{1,3}%' | sed -e 's/%//')

# Print \f1%s\fr \br %s \\br %s
echo "\r \f4\fr $mem MB \f4\fr $vol \f4 $bat" "\c \f5$date" 
#echo "\r \f4$mstat\fr $music \f4\\ue09f\fr $root \f4\\ue0b2\fr $home \f4\ue020\fr $mem \f4\\ue05d\fr $vol \f4\ue015\fr $date "
}

while read -t 1 -r wmout || true; do
    if [[ $wmout =~ ^(([[:digit:]]+:)+[[:digit:]]+ ?)+$ ]]; then
        read -ra desktops <<< "$wmout"

        tmp=
        for desktop in "${desktops[@]}"; do
            IFS=':' read -r d w m c u <<< "$desktop"
            # Tags labels
            label=${tags[$d]}
            # Current desktop color and enclosing char (yes/no)
            ((c)) && fg="8" bg="2" lc="\u6 " rc=" \ur" && layout="\f8""${layouts[$m]}" || fg="9" bg="0" lc=" " rc=" "
            # Has windows ?
            ((w)) && ((! c)) && fg="9" lc="\u5 " rc=" \ur"
            # Urgent windows ?
            ((u)) && fg="0" bg="2" lc="\u4 " rc=" \ur"

            tmp+="\f$fg\b$bg$lc$label$rc\fr\br"
        done

        tmp+=" $layout"
    fi
    echo "$tmp $(statusbar)"
done < "$ff" | bar &

$wm > "$ff" 

rm $ff
