#!/bin/bash

RPORT=9091
LPORT=9092

ssh -C -c blowfish -f fedbuild -L $LPORT:localhost:$RPORT -N

if [ 'x'$1 == 'x' ];
    then
        echo "Connection established"
    else
        echo "Connection failed"
fi
