#!/bin/bash

RPORT=9091
LPORT=9092

ssh -C -c blowfish -f deb -L $LPORT:localhost:$RPORT -N

if [ 'x'$1 == 'x' ];
    then
        echo "Fuckoff, I won't launch"
    else
        /usr/bin/transgui
fi
